// Generated by tools/gen_transforms.py from the author's AR_Ref_AliasScript.psc (SetItemTransform). Do not edit.
// { the author's AR_DogUp branch, { substrings of the model path (case-insensitive) }, always, pos xyz, rot xyz (degrees), scale }
{ 60, { "frostbitevenom" }, false, { -2.5f, -11.5f, 5.5f }, { 13.5f, 24.5f, -105.0f }, 1.0f },
{ 60, { "health01", "stamina01", "magicka01", "silence01", "command01", "rate01", "recovery01", "calm01" }, false, { -1.0f, -7.5f, 3.5f }, { 13.5f, 24.5f, -105.0f }, 1.0f },
{ 60, { "health02", "stamina02", "magicka02", "silence02", "command02", "rate02", "recovery02", "calm02" }, false, { -1.5f, -11.0f, 4.5f }, { 13.5f, 24.5f, -105.0f }, 1.0f },
{ 60, { "linger01" }, false, { -1.0f, -7.5f, 3.5f }, { 13.5f, 24.5f, -105.0f }, 1.0f },
{ 60, { "poisonweakness" }, false, { 0.0f, -3.5f, 3.0f }, { 13.5f, 24.5f, -105.0f }, 1.0f },
